





<html>
<head>
  <title>E-Revenue Receipt</title>
  <style>
  
  
    body {
      font-family: Arial, sans-serif;
    }
    .receipt {
      width: 100%;
      max-width: 500px; /* Adjust as per your receipt width */
      margin: 0 auto;
      padding: 10px;
      border: 1px solid #000;
      }
    .receipt-logo, .receipt-barcode {
      text-align: center;
      margin-bottom: 10px;
    }
    .receipt-logo img, .receipt-barcode img {
      max-width: 20%;
      height: auto;
    }
    .receipt-header {
      text-align: center;
      margin-bottom: 10px;
    }
    .receipt-body {
      margin-bottom: 10px;
    }
    .receipt-item {
      margin-bottom: 5px;
      text-align: center;
    }
    .receipt-item span {
      display: block;
      margin-bottom: 3px;
    }
    .receipt-footer {
      text-align: center;
    }
  </style>
</head>
<body>
     <div class="watermark">
  <div class="receipt">
    <div class="receipt-logo">
      <img src="logo.jpg" alt="C">
    </div>
    <div class="receipt-header">
      <h1>GOMBE STATE INTERNAL REVENUE SERVICE</h1>
      <h1><hr style="color: #000;">E-Revenue Receipt</h1>
    </div>
    <h2 style="font-weight: normal;">
    <div class="receipt-body">
      <div class="receipt-item">
        <span><strong>Revenue Head:</strong><br/> {{ $invoice->agency }}</span>
        <span><strong>Revenue Subhead:</strong> <br/>{{ $invoice->revenue_item_name }}</span>
        <span><strong>Narration:</strong> <br/>{{ $invoice->details }}</span>
      </div>
      <div class="receipt-item">
        <span><strong>Payer's Name:</strong> <br/>{{ $invoice->taxpayer_name }}</span>
        <span><strong>Payer's Phone:</strong> {{ $invoice->phone_number }}</span>
      </div>
       <div class="receipt-item">
        <span><strong>RRR:</strong> <br/>{{ $invoice->transaction_ref }}</span>
        
      </div>
      <div class="receipt-item">
        <span><strong>Date:</strong>{{ $invoice->created_at }}</span>
        <span style="font-weight: bold;"><strong>Amount Paid:</strong><br> {{ $invoice->rate }}</span>
      </div>
    </div>
    <div class="receipt-barcode">
      <img align="right"
                src="data:image/png;base64, {{ base64_encode(QrCode::format('png')->generate('Name: ' . $invoice->taxpayer_name . ' | Phone Number: ' . $invoice->phone_number . ' | Amount: ' . $invoice->rate . ' | Revenue Item: ' . $invoice->revenue_item_name . ' | Agency Name: ' . $invoice->agency_name)) }}"
                alt="QR" width="150" class="logo" />
    </div>
    <div class="receipt-footer">
      <p>Generated By: {{auth()->user()->name }}</p>
    </div>
  </div>
</h2>
</div>

</body>