<x-default-layout>

    @section('title')
        Invoices
    @endsection

    <div class="card">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-6">
            <!--begin::Card title-->
            <div class="card-title">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <!-- {!! getIcon('magnifier', 'fs-3 position-absolute ms-5') !!} -->
                    <!-- <input type="text" data-kt-user-table-filter="search" class="form-control form-control-solid w-250px ps-13" placeholder="Search Invoice" id="mySearchInput"/> -->
                </div>
                <!--end::Search-->
            </div>
            <!--begin::Card title-->

            <!--begin::Card toolbar-->
            <div class="card-toolbar">
                <!--begin::Toolbar-->
                <!-- <div class="d-flex justify-content-end" data-kt-user-table-toolbar="base">
                   You can add additional buttons or actions here 
                </div> -->
                <!--end::Toolbar-->
            </div>
            <!--end::Card toolbar-->
        </div>
        <!--end::Card header-->

        <!--begin::Card body-->
        <div class="card-body py-4">
            <!--begin::Table-->
            <div class="table-responsive">
                <table id="kt_datatable_responsive" class="table table-striped border rounded gy-5 gs-7">
                    <!-- The table headers will be automatically generated by Yajra DataTable -->
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Taxpayer Name</th>
                            <th>Agency Name</th>
                            <th>Subhead Name</th>
                            <th>Rate</th>
                            <th>Transaction Ref</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{ $dataTable->table() }}
                    </tbody>

                    <tfoot>
                        <tr class="fw-bold fs-6">
                            <th colspan="3" class="text-nowrap align-end">Total:</th>
                            <th colspan="2" class="text-danger fs-3"></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!--end::Table-->
        </div>
        <!--end::Card body-->
    </div>


    @foreach(getGlobalAssets() as $path)
    {!! sprintf('<script src="%s"></script>', asset($path)) !!}
    @endforeach
    <!--end::Global Javascript Bundle-->

    <!--begin::Vendors Javascript(used by this page)-->
    @foreach(getVendors('js') as $path)
        {!! sprintf('<script src="%s"></script>', asset($path)) !!}
    @endforeach
    <!--end::Vendors Javascript-->

    <!--begin::Custom Javascript(optional)-->
    @foreach(getCustomJs() as $path)
        {!! sprintf('<script src="%s"></script>', asset($path)) !!}
    @endforeach
    <!--end::Custom Javascript-->

    @stack('scripts')

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.5/datatables.min.js"></script>
        



    @push('scripts')

        <script>
            
    $(document).ready(function () {
    var table = $('#kt_datatable_responsive').DataTable({
        processing: true,
        serverSide: true,
        paging: false,
         dom: 'lBfrtip',
        ajax: "{{ route('invoices.index') }}",       
        columns: [
            { data: 'id', name: 'id' },
            { data: 'taxpayer_name', name: 'taxpayer_name' },
            { data: 'agency_name', name: 'agency_name' },
            { data: 'revenue_item_name', name: 'revenue_item_name' },
            { data: 'rate', name: 'rate' },
            { data: 'transaction_ref', name: 'transaction_ref' },
            { data: 'created_at', name: 'created_at' },
            // { data: 'action', name: 'action', orderable: false, searchable: false },

        ],
        
        drawCallback: function (settings) {
            // Calculate total
            console.log(settings.json);
            var api = this.api();
            total = api.column(4, { page: 'current' }).data().reduce(function (a, b) {
                return a + parseFloat(b);
            }, 0);

            // Update total in the footer
            $('tfoot tr th:eq(1)').html('Total: ' + total.toFixed(4));

            $('[data-bs-toggle="tooltip"]').tooltip();
        }
    });

    table.buttons().container().appendTo('#kt_datatable_responsive_wrapper .col-md-6:eq(0)');
});
                
        </script>
    @endpush

</x-default-layout>
